### ISSUE TITLE
Add support for exif

### ISSUE THREAD

**Issue by githubcdr** [Hermsi1337/docker-fpm-php#13]
Hi,

Thanks for your work on the PHP image. Is there any chance you can add the php7-exif module?

Wordpress 5.2 seems to like this module be available in the new site-health function.

Regards,

**Comment by Hermsi1337** [comment]
Hey,

I really appreciate your feedback and I'm glad that you're using my image.

Adding `exif` should not be a problem. I will try to add it today!

Regards,

**Comment by githubcdr** [comment]
Great, thanks!

Your images are really clean and they work very well in Kubernetes, so thank you.

**Comment by Hermsi1337** [comment]
As soon as you pull the image again, there is `exif` available @githubcdr
